### ISSUE TITLE
Wrong buffers order

### ISSUE THREAD

**Issue by Shatur** [akinsho/nvim-bufferline.lua#135]
When a new buffer is opened, it will open at a random location. For example:

1. I opened `init.lua`:
![изображение](https://user-images.githubusercontent.com/22453358/124357457-34574500-dc24-11eb-8d6a-7940907aa276.png)
2. Then I opened `dap-repl.lua`:
![изображение](https://user-images.githubusercontent.com/22453358/124357472-3faa7080-dc24-11eb-91c7-b610c5f36d8a.png)
3. Then I opened `python.lua`:
![изображение](https://user-images.githubusercontent.com/22453358/124357479-489b4200-dc24-11eb-8640-088331808ac9.png)
4. And then I opened `gitcommit.lua`:
![изображение](https://user-images.githubusercontent.com/22453358/124357490-52bd4080-dc24-11eb-9d51-68a04b9fff3a.png)

As you can see, `gitcommit.lua` is opened before `python.lua`. I would assume that it opened alphabetically, but `init.lua` is still unsorted. Usually new buffers (tabs) opened next to the current buffer (tab). Can I somehow achieve this behavior?

**Comment by akinsho** [comment]
@Shatur by default buffers are rendered based on the listing valid buffers with no specific order in mind. If you want to order them by some criteria you can use the sort_by function and order by buffer ID

**Comment by Shatur** [comment]
Okay, thank you!
We already have "extension", "relative_directory" and "directory" sorters. Maybe such sorter can be built-in too? This is the default behavior in most editors.

**Comment by akinsho** [comment]
@Shatur that's not a bad idea, I honestly didn't think anyone particularly minded tbh 🤷🏾 this should be fixed by 6526dec

**Comment by Shatur** [comment]
> this should be fixed by 6526dec

@akinsho, hm... I tried to specify the following:

```lua
    persist_buffer_sort = true,
    sort_by = "id",
```

But the issue still exists. Am I doing something wrong?

**Comment by akinsho** [comment]
@Shatur persist buffer sort is not a requirement for the ID usage also it is set by default, so you don't need to set it manually. One reason you might still be seeing this is if you had actually persisted a sort before and are re-using the same session. The sort order is stored if you manually changed the sort at some point and are using the same session.

To check this you can check the value of `g:BufferlinePositions` if it exists the run `unlet g:BufferlinePositions` and try again.

**Comment by Shatur** [comment]
> persist buffer sort is not a requirement for the ID usage also it is set by default, so you don't need to set it manually. 

Got it, thanks. Tried it again with `sort_by = "id"` set and the result is the same (e.g. the issue is exists).

> To check this you can check the value of g:BufferlinePositions if it exists the run unlet g:BufferlinePositions and try again.

@akinsho No, the variable is not set.

**Comment by Shatur** [comment]
My buffers looks like the following when I just my `init.lua`:

![изображение](https://user-images.githubusercontent.com/22453358/124389959-2bcd4000-dcf2-11eb-9547-a144862afc89.png)

Probably lua files just indexed by LSP and it messes order because it relies on the buffer id. So the id is not a reliable way to handle order.
Probably we should manually store the order of opened buffers. What do you think?

**Comment by akinsho** [comment]
@Shatur tbh that is a path I really don't want to go down, certainly for something that to me doesn't feel like a big problem. As far as I know neovim buffer ids increase monotonically i.e. 2->3->4 etc. and if a buffer is wiped out the next new buffer doesn't take an old ones place but instead increments upwards still, so new buffers should have a higher buffer id, so to me they are a good way to solve this issue.

I'm no longer entirely sure of what particular issue you are seeing. In my case with this new change I've added every new buffer appears at the end of the buffer list which I thought was the issue. Can you clarify what behaviour you are still seeing?

Re. storing some state or building new mechanisms that don't really exist in vim but only in this plugin, that seems like a significantly more complicated solution. I don't like having to maintain a list of when buffers were opened and maintaining this internal state that isn't really backed by or verifiable by something in vim proper.

**Comment by Shatur** [comment]
@akinsho, yes, your point is totally understandable. But probably buffer id is not a reliable way to sort buffers. Let's consider the following example:

1. Open buffer `A`.
2. `:bd`
3. Open buffer `B`.
4. Open buffer `A` again.

The buffer `B` will appear before the buffer `A`.
Yes, if I wipeout the buffer B, it will appear after the buffer `A`. But simple deletion is used much more often.

**Comment by akinsho** [comment]
@Shatur tbh I think that most of the time this will behave like people would expect, except for this case you describe, which personally seems fine to me since each buffer has a specific position in the list and so to me, it seems right that it would take the position it had before 🤷🏾‍♂️. I think the jump in complexity to iron out this edge case isn't worth it, for me personally anyway. I wouldn't turn down a PR, but I expect that any solution is bound to be quite heavy and still have its own edge cases.

**Comment by nyngwang** [comment]
Oh, one step close to a better plugin :/ I have the same issue.
